typography_spectrum: 0.5895
color:
  brandColors:
    - '#0e0e0e'
    - '#ed372b'
    - '#e6b787'
    - '#627587'
    - '#564532'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74714
analytics:
  google: UA-71571272-2
  facebook: null
  twitter: null
name: Woakin
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Joaquin Gonzalez
description: ¿En qué creo?
purpose: []
