name: Woakin
favicon: null
layout_spectrum: 0.91767
typography_spectrum: 0.45956
title: Cambiando de tema
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71571272-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0e0e'
    - '#ed372b'
    - '#e6b787'
    - '#627587'
    - '#564532'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
