analytics:
  google: UA-71571272-2
color:
  brandColors:
    - '#0e0e0e'
    - '#ed372b'
    - '#e6b787'
    - '#627587'
    - '#564532'
  brandStrength: 0.5625
  lightness: 0.375
  rhythmicContrast: 0.5
  saturation: 0.5625
cta: {}
layout_spectrum: 0.688322
name: Woakin
opengraph: {}
purpose: []
typography_spectrum: 0.5895
