name: Woakin
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28028
title: Cambiando de tema
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71571272-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0e0e'
    - '#ed372b'
    - '#e6b787'
    - '#627587'
    - '#564532'
  brandStrength: 0.6875
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
