typography_spectrum: 0.14738872228190303
color:
  brandColors:
    - '#DDDCC5'
    - '#958976'
    - '#611427'
    - '#1D2326'
    - '#6A6A61'
  brandStrength: 0.35734568536281586
  lightness: 0.9813822717405856
  saturation: 0.18171429028734565
  rhythmicContrast: 0.35093347798101604
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.0444353511556983
analytics:
  google: UA-71571272-2
  facebook: null
  twitter: null
name: Woakin
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Joaquin Gonzalez
description: ¿En qué creo?
purpose: []
